### ISSUE TITLE
Modules translation

### ISSUE THREAD

**Issue by KSuondProject** [duxenmx/E_ink_dashboard#12]
Hi all,

Finally my dashboard works great, but obviously all the descriptions are in english and I need to translate all in italian (but it will possible to every language).

I'm starting to evaluate to use a string replace in every single module, like this:

```
cal_n_m = calendar.month_name[cal_month]
    for r in (("December", "Dicembre"), ("January", "Gennaio"), ("February", "Febbraio"), ("March", "Marzo"), ("April", "Aprile"), ("May", "Maggio"), ("June", "Giugno"), ("July", "Luglio"), ("August", "Agosto"), ("September", "Settembre"), ("October", "Ottobre"), ("November", "Novembre")):
        cal_n_m_it = cal_n_m.replace(*r)
................................
 draw.text((cal_s_x + 60, cal_s_y-65), str(cal_n_m_it) + ' ' + str(cal_year),
              font=font_size(35), fill=color_1)
```

Where I've replace the month one-to-one from English to Italian.
It doesn't works, but I'm really new in python language so probably I've missed something.
Anyone can help me to generate a function to translate the description?

Thank you.

**Comment by KSuondProject** [comment]
Great news, after importing:

```
import locale
locale.setlocale(locale.LC_ALL, 'it_IT.-UTF8')
```
in all py modules (weather, functions, ecc) the date and time are translated! 
Remains the weather descriptions, but I think that need a proper function to analyze the data received from API to translate before placing on the display.

**Comment by KSuondProject** [comment]
Another update, in all modules I've changed the line when the time was declared in 0-12AM/PM format and the data order (day, month, year in Italy) and I've translated some other little things like the "UPDATED:" in the meeting form.
Is really beautiful now!! :sunglasses: 
Remains only the weather description but I don't know if I can do this function myself.

![1609344999430](https://user-images.githubusercontent.com/70426429/103366754-b757e100-4ac3-11eb-920e-9215e1aed931.jpg)

**Comment by duxenmx** [comment]
that s awesome!, we'll be sure to add that to the next commit

for the weather descriptions I just checked the weather api and they do provide multilingual support so that saves us some work

in the line 12 of the db_weather.py change it to this
'&exclude=hourly,minutely,alerts&lang=it'

**Comment by KSuondProject** [comment]
> that s awesome!, we'll be sure to add that to the next commit
> 
> for the weather descriptions I just checked the weather api and they do provide multilingual support so that saves us some work
> 
> in the line 12 of the db_weather.py change it to this
> '&exclude=hourly,minutely,alerts&lang=it'

You're the best man!!! Changing that line in the file as translated the weather description!! Not all, but 90%... Some description has "rain and snow" is not translated but it's not a problem, this condition comes rarely in the year.

I'm so excited for the next commit!! :star_struck: 
Now I would try to made a little variant of this project for a 5.3" display with only one modules at time, just Spotify module and a module where I'll write the indoor and outdoor temperatures using a DS18B20 sensors. Maybe I'll ask to you some more question the future for this update, if I can. I will try work on this, Is my first project on raspberry and Is really interesting and exciting!

For now really really thanks for your help! @duxenmx without your help I wouldn't have been able to do any of this! :top:
