### ISSUE TITLE
Help for projcet based on E_Ink_dashboard

### ISSUE THREAD

**Issue by KSuondProject** [duxenmx/E_ink_dashboard#15]
Hi @duxenmx!

Can I please ask help for a new project?
Is based on your code but without a server, just spotify service and a DHT22 sensor.
I've trying to refresh the screen when I change the spotify song but I've some serious problem with the get_spot_info() because it write always the same info and it doesn't change. Can I send you my code for a quick review please?
I'm stuck up over 2 weeks, I really don't know how to exit.
I hope in your help... :cry:

**Comment by duxenmx** [comment]
Hi there

Sorry, been quite busy with work and other things, sure I'll see what I can do, do you have a GitHub where I can see the code?

**Comment by KSuondProject** [comment]
Unfortunately not, but I'll learn how to upload on GitHub as soon as I can and let you know!! Really really thanks man!!!

**Comment by KSuondProject** [comment]
Hi @duxenmx !!
I've put my code on Github and I've sent to you an invite to see it! 
I published the code as private because it is badly written and I would be ashamed if someone else saw him! :laughing: 

Thanks again for the support! See you there!!

**Comment by duxenmx** [comment]
heya, havent run the code yet, have to reinstall a lot of stuff for my editor but from what I see in the test.py line 86-106, once it loads for the first time you getting information on the console for the start_counter, prev_song, curr_song, right?, once it the sleep time passes are you getting different information everytime it refreshes?

time.sleep is in seconds, so having time.sleep(5.0) is only seconds, if this was minutes it would be time.sleep(5*60) if that was your intent

start with this and let me know

**Comment by KSuondProject** [comment]
My intent with this function is read the title of the song in the prev_song variable than wait 20 secs (declared in def function of d_spoti.py). In a loop this function control if the prev_song is equal to curr_song; if the control is true do nothing, if the control is false the song has changed and so the screen write a new image with the new template.
The problem now is that the spoti function return always the same title of the song and they never change and I really don't know why they remain the same. I was think that every time the while loop read the variables the prev_song and curr_song were refreshed but it doesn't happen. There something wrong in the grammar of the code?

the time.sleep(5.0) can be deleted, it isn't useful.

**Comment by duxenmx** [comment]
I'll be closing this issues and can follow through on your project github if more assistance is needed in the future

**Comment by KSuondProject** [comment]
Sorry for the delay, ok thank you. See you soon!
