### ISSUE TITLE
Time data error in west-europe

### ISSUE THREAD

**Issue by 123tio** [duxenmx/E_ink_dashboard#6]
Hi Adrian,

can you help with this problem?
After the installation i try to start the dashboard.py with cmd:

python3 dashboard.py

It seems that the meetings section throw an error like following:

![image](https://user-images.githubusercontent.com/33313288/102006239-d282cc80-3d1f-11eb-9d86-4eb90ce427be.png)

**Comment by duxenmx** [comment]
hey there
lets troubleshoot
-go to the d_functions.py
-line 169 type it like this 
print(utc_datetime)
date_time_x = datetime.datetime.strptime(str(utc_datetime), '%Y-%m-%dT%H:%M:%S%z')
-save the script, and run dashboard.py again
-let me know what the console throws you

**Comment by 123tio** [comment]
![image](https://user-images.githubusercontent.com/33313288/102008171-ee419f00-3d2e-11eb-9135-74b21079731a.png)

**Comment by 123tio** [comment]
when i print out:
![image](https://user-images.githubusercontent.com/33313288/102008362-1087ec80-3d30-11eb-9556-1c517c4106cc.png)
i get the same:
![image](https://user-images.githubusercontent.com/33313288/102008371-22698f80-3d30-11eb-8e76-eaad341b1cf5.png)

**Comment by duxenmx** [comment]
mmm, seems that you found a bug when choosing full day events, I'll work on it and submit the solution in the next release, in the meanwhile test it by just creating events for certain times

**Comment by duxenmx** [comment]
alright, It seems its working now when having full day events, I updated the files in the github, you only need to overwrite the d_functions and db_g_meetings files

give them a try

**Comment by 123tio** [comment]
Wow. It work's perfectly. Thx a lot. What a cool project. 
Have a nice day.
Issue can be closed

**Comment by duxenmx** [comment]
Coolio have a good one
